---
  # Trecho da instalação, pode ser removido caso não haja necessidade
  - name: Download para RHEL like
    yum:
      name: ntp
      state: latest
    when: ansible_pkg_mgr == 'yum'

  - name: Download para SUSE like
    zypper:
      name: ntp
      state: latest
    when: ansible_pkg_mgr == 'zypper'

  - name: Download para Debian like
    apt:
      name: ntp
      state: latest
    when: ansible_pkg_mgr == 'apt'
  # Fim do trecho da instalação

  - name: Transferir arquivo template ntp
    template: 
      src: templates/template_conf.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
      backup: yes
    notify: 
      - Restart_NTP_RHEL_Suse
      - Restart_NTP_Debian
...