---
  # Adicione os servidores NTP que utiliza nestas variaveis.
  # Caso não utilize algo especifico serão utilizados os servidores das variaveis defaults.
  ntp_server1:
  ntp_server2:
  ntp_server3:
  ntp_server4:
...