---
  - name: Restart_NTP_RHEL_Suse
    service: 
      name: ntpd
      state: restarted
      enabled: yes
    when: ansible_os_family == 'RedHat' or ansible_os_family == 'Suse'

  - name: Restart_NTP_Debian
    service: 
      name: ntp
      state: restarted
      enabled: yes
    when: ansible_os_family == 'Debian'
...
